### ISSUE TITLE
Aborted steal

### ISSUE THREAD

**Issue by akdjka** [ja2-stracciatella/ja2-stracciatella#789] opened 2019-02-23 10:18 UTC
In the attached save, try to make Johny steal enemy weapon.
There's the clock spinning for a long while and then the action seems aborted. The APs are taken but the steal neither succeeds nor there's a message of it failing.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  f970499b5 | JA2 Gold En  |        |      |

[s.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2896696/s.zip)

**Comment by lynxlynxlynx** [comment] 2020-06-05 21:14
The clock has been fixed, but I haven't been able to successfully steal with this save. `UseHandToHand` doesn't even get to calculating steal chance, since it can't find the target. Because they're on the roof and bTargetLevel is 0 for the target (should be >0) this call fails:

```
SOLDIERTYPE* const pTargetSoldier = WhoIsThere2(sTargetGridNo, pSoldier->bTargetLevel);
```

Manually calling with 1 does work. 

I then tried stealing from someone on the ground and it again didn't work — their level is 1 instead of 0. So just the reverse problem. The second ground soldier I found was fine. Same with soldiers from other saves.

It could be we are not updating the level properly in some cases, but so far it seems like a broken save. Closing, reopen if you find a reproducible case from a different game.

**Closed by lynxlynxlynx** 2020-06-05 21:14 UTC
Labels: bug, retest
