### ISSUE TITLE
AP costs are shown incorrectly over the movement cursor in turn-based mode

### ISSUE THREAD

**Issue by DSeyka** [ja2-stracciatella/ja2-stracciatella#645] opened 2017-12-21 01:01 UTC
See the screenshot:

![image](https://user-images.githubusercontent.com/34726992/34235471-f9b1f550-e602-11e7-934d-0063a6a4eca9.png)

Seyka is about to run a single tile "diagonally" which should (and will, so **it's only miscalculated when showing APs to spend, the actual number spent is correct**) cost 3 APs, but shows the cost as 8 APs.

This happens to all mercenaries, regardless of stance, movement mode or distance, and only when pre-calculating movement costs as shown above; it seems to be adding 5 "extra" APs over the actual numbers in all these cases, but e.g. aiming and shooting isn't affected and works as expected.

Checked on Windows 10 with a nightly build (ja2-stracciatella_0.16.0-20171217_win-msvc64.zip) and a release one (ja2-stracciatella_0.16.0_win-msvc64.zip), both found on http://builds-ja2.stefanlau.com/

**Comment by lynxlynxlynx** [comment] 2017-12-21 20:24
This is most probably a regression within this release, so more exploring is needed.

**Comment by DSeyka** [comment] 2017-12-21 22:15
Did some downloading and testing, the issue is present since this nightly:
ja2-stracciatella_0.15.x-20171108_win-msvc64.zip
(NOT present in ja2-stracciatella_0.15.x-20171106_win-msvc64.zip and a couple of previous ones)

**Comment by selaux** [comment] 2017-12-28 10:34
I have a bad feeling that this was caused by the Whitespace Refactoring (https://github.com/ja2-stracciatella/ja2-stracciatella/commit/e4faa6ae4a3567dc91a708c456cd4c210eabf96b), which was merged that day...

**Comment by selaux** [comment] 2017-12-28 11:01
Allright, for me it is the whitespace commit (https://github.com/ja2-stracciatella/ja2-stracciatella/commit/e4faa6ae4a3567dc91a708c456cd4c210eabf96b) that broke this. The bug isn't there with it's parent commit (https://github.com/ja2-stracciatella/ja2-stracciatella/commit/5cdc23baf5850d43b072a9bdc7ff8700fab7bd43). Can somebody else verify? I don't see any semantical changes in `Points.cc` though. It is also weird that this only happens when displaying the APs, not when they are actually deducted...

**Comment by DSeyka** [comment] 2017-12-28 12:59
Yep, looks like that's it.
ja2-stracciatella_0.15.x-611pullrequest_win-msvc64.zip has the bug,
ja2-stracciatella_0.15.x-556pullrequest_win-msvc64.zip doesn't.

**Comment by lynxlynxlynx** [comment] 2017-12-28 13:03
My guess would be bad merge conflict resolution. I'll take a look later.

**Comment by Manuel-K** [comment] 2017-12-28 13:36
The problem is in the function `PlotPath` in `src/game/Tactical/PathAI.cc`. It works after restoring that single function to the previous version. I'm currently searching for the problematic change.

**Comment by DSeyka** [comment] 2017-12-28 13:40
Line 2049 in new file:
sAnimCost = AP_GET_UP;
It isn't commented like in the original file. That has to be it.

**Comment by Manuel-K** [comment] 2017-12-28 13:42
Correct.

**Closed** 2017-12-28 13:49 UTC
Labels: bug, critical, non-vanilla

**Comment by Manuel-K** [comment] 2017-12-28 13:52
Funny. That should have been a PR. I don't know why it didn't work correctly. It seems that the web UI has problems with a very slow internet connection.

**Comment by Manuel-K** [comment] 2017-12-28 14:08
@DSeyka: Thank you for the report and the debugging.

**Comment by DSeyka** [comment] 2017-12-28 14:28
You're welcome!
So barring compiling the whole thing myself, is there any way I could test this some more with this bug fixed already? Or do I have to wait for the next nightly?

**Comment by derSteFfi** [comment] 2017-12-28 14:32
If you don't want to compile it yourself, you'll have to wait for the nightly.

**Comment by selaux** [comment] 2017-12-28 18:45
Updated the release tag, new builds should become available within the next 30mins here: http://builds-ja2.stefanlau.com/releases/
