### ISSUE TITLE
Game is caught in infinite stopwatch

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#650] opened 2017-12-22 21:04 UTC
My current playtest with DiD mode ended up in an infinite stopwatch. I was talking to Michy in the Bar in San Mona (C5). At the same time, I was sending some mercs around the map to investigate/loot the buildings Micky's speech was interrupted by a query for a locked door. Now, it is impossible to continue this game. Whatever happened, it is totally game-breaking.

[SaveGame11.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1583464/SaveGame11.zip)

**Comment by lynxlynxlynx** [comment] 2017-12-22 21:10
This sounds like something that might have been broken from the start. Is it easy for you to reproduce?

**Comment by RinneT** [comment] 2018-01-03 11:22
This bug was actually the reason why I implemented the backup function in the first place.
IIRC it would always happen when you talk to someone and another merc causes a popup screen in the meantime.
However I can't reproduce it anymore.

I'll see if I can at least put in a check for the stopwatch.

**Comment by JAsmine-ja2** [comment] 2018-01-03 11:26
How does the bbackup function work again? ^^'

**Comment by RinneT** [comment] 2018-01-03 11:32
It creates a "Backup" Folder in the savegames folder. That one contains the last two saves as savegamename.sav.1 and savegamename.sav.2
Copy them to the root SavedGames folder and remove the .1 or .2

Problem could be if you loaded and saved the game multiple times, it will overwrite them with the stopwatch game. Good idea to rename the backup folder to make sure they aren't overwritten.

**Comment by lynxlynxlynx** [comment] 2018-01-03 18:22
So now part of this is fixed, thanks Rinne!

**Comment by lynxlynxlynx** [comment] 2020-05-27 10:49
Closing as a dupe of #427.

**Closed** 2020-05-27 10:49 UTC
Labels: bug, duplicate, minor
