### ISSUE TITLE
Some rectagle rendered on top of the help screen

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#187] opened 2015-10-13 05:31 UTC
Originally reported by: **Agatae Tsag (Bitbucket: [Agatae](http://bitbucket.org/Agatae), GitHub: Unknown)**

---

In the middle of the screen, on top of text there's some rect.

---
- Bitbucket: https://bitbucket.org/gennady/ja2-stracciatella/issue/187

**Comment by derSteFfi** [comment] 2016-02-20 09:35
I can not confirm this, help screen looks fine for me on master in tactical and strategic. also tried all help topic, fine readable texts without rectangles everywhere.
someone else who can confirm?

**Comment by JAsmine-ja2** [comment] 2019-01-26 15:13
The help screen looks fine in my game (JA2S 0.16.0 win64 / JA2 1.12 Gold English). The screenshot in the original report is not available anymore. Shall we close this one?

**Comment by selaux** [comment] 2019-01-28 07:16
@JAsmine-ja2 Yes lets close.

**Closed by selaux** 2019-01-28 07:16 UTC
Labels: bug, major, retest

**Comment by JAsmine-ja2** [comment] 2019-02-05 20:31
![screen000](https://user-images.githubusercontent.com/17213795/52302331-289cc100-298d-11e9-920d-0e82df7c9ece.jpg)
![screen002](https://user-images.githubusercontent.com/17213795/52302333-29cdee00-298d-11e9-94a4-638379fabf37.jpg)

Seems like this bug is legit after all. I didn't provide a savegame, because I'm unsure how to reproduce these graphical artifacts.
The helpscreen seems to be okay most of the time. By clicking around and spamming the 'h' key, I'm sometimes able to mess the helpscreen up a bit.

**Comment by momoko-h** [comment] 2022-11-16 10:20
I found a reliable way to see this bug: in tactical, press V to bring up the game information messages, press H, then use the arrow buttons to scroll. You'll see a small rectangle over the text where the longest message string would be (you might have to use a low resolution like 640x480). Either there is a problem with background save system or the help screen is using it incorrectly.
