### ISSUE TITLE
Autosaving / SavegameScreen Layout

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#302] opened 2016-05-06 19:51 UTC
EDIT (@dersteffi):
Should we make autosaving at the end of a tactical turn a standard game option and shall we display those autosaves in the savegame screen? If yes, in what manner esspecially regarding #308 ?
/EDIT

It seems like JA2's autosave function doesn't work properly with Stracciatella.
When I create the autosave.pls file in JA2's folder, autosaves are created as expected. However, trying to load the autosaves crashes the game.
The autosaves themselves seem to be okay, since I can load them from JA2 (without Stracciatella).

I know that JA2's autosave feature is not used by many players, since it is not properly documented. It would still be good if Stracciatella could support this feature.

**Comment by derSteFfi** [comment] 2016-05-07 08:48
OK, my thoughts here:
This is generally a good idea. I needed some time to figure out how to get this working, so we should document it much better. Currently, this doesn't work because of unimplemented functions:

```
===> sgp/FileMan.cc:413: GetFileManFileTime() is not implemented

Thread 1 "ja2" received signal SIGABRT, Aborted.
0x00007ffff6d182a8 in raise () from /usr/lib/libc.so.6
(gdb) backtrace
#0  0x00007ffff6d182a8 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff6d1972a in abort () from /usr/lib/libc.so.6
#2  0x000000000069d511 in GetFileManFileTime (f=0x28e8690, pCreationTime=0x7fffffffbb20, pLastAccessedTime=0x7fffffffbb10, pLastWriteTime=0x7fffffffbb00)
    at sgp/FileMan.cc:413
#3  0x00000000004a0f16 in GetNumberForAutoSave (fLatestAutoSave=1 '\001') at Build/SaveLoadGame.cc:2563
#4  0x00000000004a211b in GetSaveLoadScreenUserInput () at Build/SaveLoadScreen.cc:617
#5  0x00000000004a1704 in SaveLoadScreenHandle () at Build/SaveLoadScreen.cc:220
#6  0x0000000000448127 in GameLoop () at Build/GameLoop.cc:299
#7  0x00000000006abd97 in MainLoop (msPerGameCycle=25) at sgp/SGP.cc:247
#8  0x00000000006ac54d in main (argc=3, argv=0x7fffffffe008) at sgp/SGP.cc:511
(gdb) 
```
This function has been implemented (by me :D) in the implementUnimplementedStuff PR (#264) . I would think it should work after the PR is merged.

**Comment by JAsmine-ja2** [comment] 2016-05-07 09:27
The feature is documented only in the Readme.doc in JA2 folder and nowhere else.

It might be an idea to implent this feature into Stracciatella and then add the autosave.pls as a mod to the ModPack with proper documentation.

**Comment by derSteFfi** [comment] 2016-05-18 17:50
I can confirm this is fixed for me with #264  If some one else confirms, I'd suggest merging the PR since I stopped working on the Blitters anyway. I can also isolate the non-Blitter stuff so we can merge it seperately and merge the blitters as soon as they are completed and/or more reviewed...

**Comment by selaux** [comment] 2016-05-30 18:48
I can config that autosaving works with #264. I think it's fine to merge as it is. We should definitely make this more prominent and include autosaves in the save game list.

**Comment by derSteFfi** [comment] 2016-05-30 21:44
autosaving could also be an option in the the option screen. including the autosaves in the save game list is good imho.

**Comment by JAsmine-ja2** [comment] 2016-05-31 16:52
An advanced implentation of this feature is a very good idea.
This could also be an option that can be enabled in the launcher?!  #270

**Comment by selaux** [comment] 2016-05-31 17:44
Maybe not even an option, we could simple create a tabbed structure for the save game menu as proposed in #308.

**Comment by derSteFfi** [comment] 2016-06-01 07:10
Or, if an Option, we could integrate it in the Options screen. To be able to deactivate it when not wanting it (takes about a second here every time)

**Comment by JAsmine-ja2** [comment] 2016-06-01 13:41
Great idea. Tabbed savegame structure is an even better solution!

**Comment by derSteFfi** [comment] 2016-06-13 09:42
Since selaux already confirmed, shall we close this?

**Comment by lynxlynxlynx** [comment] 2016-06-14 15:39
The original is fixed, but then it turned into an enhancement debate. Usually I'd close it and open a new one, but this one is already linked three times, so maybe it's better to rename it and edit the intro post.

**Comment by lynxlynxlynx** [comment] 2022-06-20 10:13
So it seems only the easy stuff remains: 
- create an empty autosave.pls in the user's config dir ourselves if it is missing
- OR just remove the check, as it seems it's just a marker file
- maybe change the autosave prefix, so it's clearer (now you end up with saves called Auto%d)

**Comment by lynxlynxlynx** [comment] 2022-08-26 14:22
So, any opinions? I'm for just removing the restriction, without hiding it behind configuration.

**Closed** 2022-10-19 21:19 UTC
Labels: enhancement
