### ISSUE TITLE
Game crashes on helicopter coming back to Drassen

### ISSUE THREAD

**Issue by njskalski** [ja2-stracciatella/ja2-stracciatella#1107] opened 2020-06-07 20:51 UTC
### What is wrong
I attach a save (both error and one to trigger it). Just load SaveGame10.sav, move Skyrider anywhere (either empty or with someone) and back to Drassen (or allow him to come back himself). You get crash:

```
2020-06-07T20:42:24 [ INFO] game/GameLoop.cc: Version #:     Build 04.12.02
2020-06-07T20:42:41 [ WARN] game/Tactical/Tactical_Save.cc: SynchronizeItemTempFile() Reported 0, should be 16
2020-06-07T20:43:13 [ WARN] game/Strategic/Scheduling.cc: Schedule callback occurred outside of tactical -- Auto processing!
2020-06-07T20:43:13 [ WARN] game/Strategic/Scheduling.cc: Schedule callback occurred outside of tactical -- Auto processing!
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to add node to world
Creating an emergency savegame succeeded (error.sav).
Please report this error with a description of the circumstances. Do not forget to attach the savegame.
fish: “./ja2” terminated by signal SIGABRT (Abort)
```

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
Both HEAD and 0.16.x, vanilla, don't know

**Comment by njskalski** [comment] 2020-06-07 20:52
[SavedGames.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/4742939/SavedGames.zip)

**Comment by lynxlynxlynx** [comment] 2020-06-07 21:25
Yeah, something with the chopper placement, Perhaps a militia is in the way? Still stepping through.

**Comment by lynxlynxlynx** [comment] 2020-06-07 22:03
`src/game/TileEngine/Structure.cc:451` return false, since both the 3 tile pDBStructure and the existing one only have `STRUCTURE_VEHICLE | STRUCTURE_MULTI` set. Perhaps we're not removing the chopper properly? Perhaps 986dd5b needs a relook with fresh eyes ...

**Comment by ja2-derek** [comment] 2020-06-08 03:41
Sounds like this - struct not cleanly removed:
 https://github.com/ja2-stracciatella/ja2-stracciatella/issues/251#issuecomment-204927197

**Comment by ja2-derek** [comment] 2020-06-08 06:33
Some more bits of information:
- It is reproducible only when the current sector is at the refueling site, i.e. you have a squad there and entered in tactical view. Otherwise the game will not even bother with AddHeliPieces and Remove stuff
- The crash happens when the 2nd Heli piece (`ostruct + 1`) got added.
- The 2nd Heli piece was not removed by `RemoveStruct(grid_no, ostruct + 1);`
   - Removal skipped because the struct has no "Base Structure"  (DeleteStructureFromWorld)
   - The struct has no base structure because sGridNo is 0 (FindStructureByID)  
   - The struct was first added with `sGridNo == 0`  because it is the BASE_TILE, i.e. first in list (AddStructureToWorld)
  - The struct is NOT marked as STRUCTURE_BASE_TILE, because the sPosRelToBase is -320 (CreateStructureFromDB)


So something seems to be contradictory - the structure base tile (pTile[0]) has sPosRelToBase of -320.

**Comment by ja2-derek** [comment] 2020-06-08 07:53
This is probably a very old bug http://thepit.ja-galaxy-forum.com/index.php?t=msg&th=14110&goto=202602&

**Comment by ja2-derek** [comment] 2020-06-08 08:16
I guess this has been an issue ever since 0.10.

http://thepit.ja-galaxy-forum.com/index.php?t=msg&th=14110&goto=202602&

According to this thread, tron seems to have addressed the "missing piece" issue but not the exception.


And indeed the `FailToAddNode` throw was added after v0.10 (https://github.com/ja2-stracciatella/ja2-stracciatella/commit/119a1d172852ca503e1dda10435e4430af73a134)

**Comment by lynxlynxlynx** [comment] 2020-06-08 09:02
Ah, so the classic of fixing one bug unearthing another. Is it a data bug in the end? The editor looks pretty useless to investigate this.

**Comment by ja2-derek** [comment] 2020-06-08 09:08
I tend to believe it is. It's probably the .JSD file...

Or just add a `catch` clause, and it will be pretty much the same as pre-0.11 behaviour.

**Comment by lynxlynxlynx** [comment] 2020-06-08 09:43
Does changing that in the editor avoid the problem?

I think this is something we should fix on load, since it should be possible to uniquely identify the structure.

**Comment by ja2-derek** [comment] 2020-06-08 09:45
I don't think it can be done in map editor. I do not see the copter there when I open B13 with map editor.

I think it is dynamically added after the game has started.

**Comment by ja2-derek** [comment] 2020-06-08 09:57
Yes it does fix the issue for me. Copter looks fine in tactical with the patched JSD.

Before patching:
![before](https://user-images.githubusercontent.com/63151803/84017601-7b3b2280-a9b1-11ea-8c9c-2800a26ed5c7.png)


After patching:
![after](https://user-images.githubusercontent.com/63151803/84017613-7d9d7c80-a9b1-11ea-80f6-2022d3a4b173.png)

**Comment by lynxlynxlynx** [comment] 2020-06-08 10:05
Great, so we just fix it programmatically in the loader and this ancient beast is done for. :)

**Comment by ja2-derek** [comment] 2020-06-08 10:46
I will make a PR.

**Closed** 2020-06-08 16:46 UTC
Labels: bug, non-vanilla, vanilla
