### ISSUE TITLE
Any way to speed up the game? (speedhack)

### ISSUE THREAD

**Issue by Kokkolar** [ja2-stracciatella/ja2-stracciatella#1093] opened 2020-05-28 20:51 UTC
Hello.
I've tried to use speedhack by Cheat Engine, but it can only to slow down the game not speed up. 

Why speedhack does not work?
Is there any other way?

Strac version 0.12.352 (build 04.12.02)

**Comment by lynxlynxlynx** [comment] 2020-05-28 21:12
Sounds like you're on some ancient version. Anyway, find where game.json was installed for you and tweak this number:
```
    //  Number of milliseconds for one game cycle.
    //  25 ms gives approx. 40 cycles per second (and 40 frames per second, since the screen is updated on every cycle).
    //  Decreasing this value will increase the speed of the game (enemy movement, bullets speed, etc).
    //  Stracciatella standard value: 25
    "ms_per_game_cycle": 25,
```

**Comment by Kokkolar** [comment] 2020-05-29 08:09
Thanks.

But this action does not make any real difference.

I should try this on newer Strac version.

**Comment by Kokkolar** [comment] 2020-05-29 09:12
Steam Gold version + Strac v0.16.1 (build 04.12.02)

Still no difference between
`"ms_per_game_cycle": 1,`
and
`"ms_per_game_cycle": 25,`

But if value set to `"500"` game become ultra slow.

**Comment by ja2-derek** [comment] 2020-06-03 22:13
@Kokkolar , which OS are you using?

**Comment by Kokkolar** [comment] 2020-06-04 17:18
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/658y5tMy/explorer-2020-06-04-19-47-26.jpg' border='0' alt='explorer-2020-06-04-19-47-26'/></a>

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/KvC41wWQ/nv-Cpl-UI-2020-06-04-20-15-40.jpg' border='0' alt='nv-Cpl-UI-2020-06-04-20-15-40'/></a>

**Comment by lynxlynxlynx** [comment] 2020-06-06 16:05
I can confirm that the setting is mostly useful for slowing things down, since most of the effects are not visible. So we can forget about this line of reasoning.

What is this cheat engine supposed to do? Does it modify the exe, use dll injection?

**Comment by Kokkolar** [comment] 2020-06-07 19:11
dll injection.

It works for Fallout 1 and XCom Enemy Within for example.

**Comment by lynxlynxlynx** [comment] 2020-06-07 19:19
Unless it has JA2:S as a supported platform, then of course it can't work. It's moot anyway, since we have the code right here.

It's clear now not everything is tied to the same clock, so to answer the original question: no / not yet.

**Comment by ja2-derek** [comment] 2020-06-27 05:19
The game speed is somehow tied to system clock. If you really want to speed up the game so it feels like running Vanilla on a modern computer. You can change the below line:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/7d66aa47554c125a250db5d27dd4f77acb513ae8/src/game/Utils/Timer_Control.cc#L139

to:
```c
g_timer = SDL_AddTimer(BASETIMESLICE / 2, TimeProc, 0); 
```

Then the game will run twice as fast (or as fast as your CPU can handle). Hope that helps your hacking.

**Comment by lynxlynxlynx** [comment] 2020-06-28 10:08
Closing as a dupe of #148, will copy the last comment there.

**Closed** 2020-06-28 10:08 UTC
Labels: question
