### ISSUE TITLE
rust vs cmake: continuous rebuilding

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#1101] opened 2020-06-06 16:20 UTC
I didn't notice it before, but if I run make twice in a row, stracciatella_c_api gets recompiled.

```
$ make
[  0%] Built target gtest
[  1%] Built target smacker
[  1%] Built target stracciatella-update-stamp
[  2%] Building stracciatella
cargo build --verbose
       Fresh autocfg v1.0.0
       Fresh unicode-xid v0.2.0
/.../
       Fresh cbindgen v0.13.2
   Compiling stracciatella_c_api v0.1.0 (/home/kajak/games/ja2-stracciatella/rust/stracciatella_c_api)
       Fresh stracciatella v0.1.0 (/home/kajak/games/ja2-stracciatella/rust/stracciatella)
     Running `/home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/debug/build/stracciatella_c_api-89b06df76dab82ff/build-script-build`
     Running `rustc --edition=2018 --crate-name stracciatella_c_api stracciatella_c_api/src/lib.rs --color always --crate-type staticlib --emit=dep-info,link -C panic=abort -C debuginfo=2 -C metadata=81623c7dafb4c0d0 -C extra-filename=-81623c7dafb4c0d0 -C rpath --out-dir /home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -C incremental=/home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/x86_64-unknown-linux-gnu/debug/incremental -L dependency=/home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/debug/deps --extern hex=/home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/x86_64-unknown-linux-gnu/debug/deps/libhex-9bf71fabcb9ec0d6.rlib --extern libc=/home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/x86_64-unknown-linux-gnu/debug/deps/liblibc-ebf2a33c586c3f32.rlib --extern stracciatella=/home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/x86_64-unknown-linux-gnu/debug/deps/libstracciatella-51b3592d923c450b.rlib --print=native-static-libs`
note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.

note: native-static-libs: -lutil -ldl -lutil -ldl -lrt -lpthread -lgcc_s -lc -lm -lrt -lpthread -lutil -lutil

    Finished dev [unoptimized + debuginfo] target(s) in 1.87s
Built target cargo-build-debug
Built target stracciatella-build
Built target ja2


$ make
[  0%] Built target gtest
[  1%] Built target smacker
[  1%] Built target stracciatella-update-stamp
[  2%] Building stracciatella
cargo build --verbose
       Fresh autocfg v1.0.0
       Fresh unicode-xid v0.2.0
/.../
       Fresh cbindgen v0.13.2
   Compiling stracciatella_c_api v0.1.0 (/home/kajak/games/ja2-stracciatella/rust/stracciatella_c_api)
       Fresh stracciatella v0.1.0 (/home/kajak/games/ja2-stracciatella/rust/stracciatella)
     Running `/home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/debug/build/stracciatella_c_api-89b06df76dab82ff/build-script-build`
     Running `rustc --edition=2018 --crate-name stracciatella_c_api stracciatella_c_api/src/lib.rs --color always --crate-type staticlib --emit=dep-info,link -C panic=abort -C debuginfo=2 -C metadata=81623c7dafb4c0d0 -C extra-filename=-81623c7dafb4c0d0 -C rpath --out-dir /home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -C incremental=/home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/x86_64-unknown-linux-gnu/debug/incremental -L dependency=/home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/debug/deps --extern hex=/home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/x86_64-unknown-linux-gnu/debug/deps/libhex-9bf71fabcb9ec0d6.rlib --extern libc=/home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/x86_64-unknown-linux-gnu/debug/deps/liblibc-ebf2a33c586c3f32.rlib --extern stracciatella=/home/kajak/games/ja2-stracciatella/build/dependencies/lib-stracciatella/target/x86_64-unknown-linux-gnu/debug/deps/libstracciatella-51b3592d923c450b.rlib --print=native-static-libs`
note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.

note: native-static-libs: -lutil -ldl -lutil -ldl -lrt -lpthread -lgcc_s -lc -lm -lrt -lpthread -lutil -lutil

    Finished dev [unoptimized + debuginfo] target(s) in 1.73s
Built target cargo-build-debug
Built target stracciatella-build
Built target ja2
```

Can we do better? It seems pointless.

**Comment by selaux** [comment] 2020-07-07 14:15
After working with the code again after some time, the current approach with the stamp file seems quite slow to me. Slower than just rebuilding the library. Can anybody confirm this?

**Comment by ja2-derek** [comment] 2020-09-21 09:05
Is this still an issue? I ran `make` twice, and the second one did close to nothing:


```
...
Building CXX object CMakeFiles/ja2.dir/src/sgp/SGPStrings_unittest.cc.o
Building CXX object CMakeFiles/ja2.dir/src/sgp/string_unittest.cc.o
Linking CXX executable ja2
/usr/bin/ld: dependencies/lib-lua/liblua.a(loslib.c.o): in function `os_tmpname':
/home/csy/Workspace/ja2-stracciatella/dependencies/lib-lua/lua/src/loslib.c:169: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
Built target ja2
$ make
[  0%] Built target stracciatella-update-stamp
[  1%] Built target stracciatella-build
[  2%] Built target ja2-launcher
[  3%] Built target gtest
[ 11%] Built target lua
[ 12%] Built target smacker
[100%] Built target ja2
$
```

**Comment by selaux** [comment] 2020-09-21 13:03
The issue is that I have some target directories (which seem to contain a bunch of things) in the rust code, that are included in the timestamp file. I excluded them the in the sccache branch, there it is fast for me again. Will close when the branch is merged.

**Comment by lynxlynxlynx** [comment] 2020-09-21 22:38
Can't say, since current master doesn't build for me (remove_dir_all-0.5.3):

> error[E0658]: `cfg(doctest)` is experimental and subject to change

**Closed** 2020-09-25 15:01 UTC
Labels: build-system

**Comment by lynxlynxlynx** [comment] 2020-09-25 15:33
Looks like I'll have to get newer rust, at least 1.46.

**Comment by selaux** [comment] 2020-09-25 15:42
That is weird. In CI (according to logs) we should be building with 1.36.0... For doctest 1.40.0 should be sufficient anyways. We could also revert to remove_dir_all 0.5.2.

**Comment by lynxlynxlynx** [comment] 2020-09-25 15:52
I'm on 1.39.0, but even wiping the cargo cache, making clean didn't help.
