### ISSUE TITLE
Long wait when soldier spots item in turn-based mode

### ISSUE THREAD

**Issue by NoFreeUsernameDammit** [ja2-stracciatella/ja2-stracciatella#1485] opened 2022-03-27 19:20 UTC
| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.18 | JA2 Gold English, 1.12 GOG  |    no    |         |

Mods: from-russia-with-love, generous-rebels, imp-quiz-honest-answers

System: Win 8.1 x64

Whenever one of my soldiers spots an item on the ground while in turn-based mode, the game gets stuck in the "hourglass" mode for about 10 seconds. Can be reproduced in the attached save by moving Buzz or Blood toward the corpses. No issue in realtime.

[QuickSave.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/8358300/QuickSave.zip)

**Comment by lynxlynxlynx** [comment] 2022-03-27 19:36
Can you try with a nightly build? A similar bug has been fixed already, so this might just be a dupe.

**Comment by ja2-derek** [comment] 2022-03-27 19:43
Might be related or dupe of https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1367.

**Comment by lynxlynxlynx** [comment] 2022-04-03 10:37
Closing as a probable dupe due to inactivity. I didn't see such problems in my testing.

**Closed by lynxlynxlynx** 2022-04-03 10:37 UTC
Labels: bug, non-vanilla
