### ISSUE TITLE
Error saving game

### ISSUE THREAD

**Issue by brainfcuk** [ja2-stracciatella/ja2-stracciatella#1472] opened 2022-03-20 09:29 UTC
FileMan::moveFile('/tmp/ja2-stracciatella-Mzs79gLM/SavedGames/2022-03-20T02:11:18Z-snafu.sav', '/home/nonroot/.ja2/SavedGames/2022-03-20T02:11:18Z-snafu.sav') failed: Fs_rename "/tmp/ja2-stracciatella-Mzs79gLM/SavedGames/2022-03-20T02:11:18Z-snafu.sav" "/home/nonroot/.ja2/SavedGames/2022-03-20T02:11:18Z-snafu.sav": Invalid cross-device link (os error 18)

**Comment by selaux** [comment] 2022-03-23 15:12
Hm, this should be handled by falling back to copying the file [here](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/rust/stracciatella/src/fs.rs#L63). Maybe the error kind in your case is not `ErrorKind::Other`? Maybe making the fallback more robust would be the best option.

**Comment by selaux** [comment] 2022-03-23 18:24
@brainfcuk Do you know by any chance which rust version was used to compile? Because there is a [specific ErrorKind](https://doc.rust-lang.org/stable/std/io/enum.ErrorKind.html#variant.CrossesDevices) for this on nightly.

**Comment by selaux** [comment] 2022-03-23 19:28
Can you check whether the build from [here](https://storage.googleapis.com/ja2-builds/index.html#pull-requests/1478/) fixes the issue?

**Comment by selaux** [comment] 2022-03-29 18:09
This was indeed caused by compiling with newer Rust versions and should be fixed in the next master release. Please reopen if there are further issues.

**Closed** 2022-03-29 18:08 UTC
