### ISSUE TITLE
Tony gun and ammo sale mismatch

### ISSUE THREAD

**Issue by nemuc** [ja2-stracciatella/ja2-stracciatella#1746] opened 2022-12-29 11:13 UTC
### What is wrong
Arms dealer Tony in C5 sells a H&K G3A3 for 1,766 . However, he doesn't sell any corresponding 7.62 mm NATO ammunition. Thus, the gun is unusable for the moment.

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  v0.20.0-git+439a6d3	| JA2 Gold GOG  |    I don't know   |     I don't know     |

Operating system: Ubuntu 22.04.1 LTS

![tony-ammo](https://user-images.githubusercontent.com/39365524/209943368-496fac37-fa0a-4621-a3ee-be32ea371103.png)

[bugreport.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/10319098/bugreport.zip)

**Comment by lynxlynxlynx** [comment] 2022-12-30 07:32
It is a vanilla thing, but it's unclear to me whether we should do anything about it.

**Comment by misanthropos** [comment] 2022-12-30 08:41
It is the black market you are buying from. This is what I would expect from a black market. Things you can not buy are either sold out or not available at the moment for other reasons. It should stay as intended (even though it has been frustrating to me too, e.g. ammo for P90 or G11 is scarce).

**Comment by momoko-h** [comment] 2022-12-30 10:04
It's strongly implied that Tony's business is anything but legitimate. He's just reselling whatever somebody else in Arulco had lying around and wanted to pawn off, so you should not expect his inventory to make any logical sense.
In the screenshot you'll notice that is also the other way around: ammunition without the matching weapons. My vote is for leave it as is, too.

**Comment by lynxlynxlynx** [comment] 2022-12-30 10:06
Alright, seems we're in agreement, so closing.

**Closed by lynxlynxlynx** 2022-12-30 10:06 UTC
Labels: wontfix, vanilla
