### ISSUE TITLE
Skyrider claims having no chopper after landing in Estoni.

### ISSUE THREAD

**Issue by misanthropos** [ja2-stracciatella/ja2-stracciatella#723] opened 2018-09-11 22:11 UTC
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
I landed in Estoni with Hitman to pick up Maddog and buy some stuff. The central SAM site is mine and I had no problem landing.
First I noticed there was no Heli to board anymore. Anyhow on the map you can click the chopper and Skyrider claims he has lost his vehicle.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  release/git | eg. JA2 Gold Dutch  |    yes/no    |    yes/no     |
[QuickSave.sav.gz](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2372891/QuickSave.sav.gz)
commit f571f92f58956749187f45531adb27754a098d6a (HEAD -> master, origin/master, origin/HEAD)
Merge: 7d66aa475 54799c6de

Vanilla: no
Used to work.

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
savegame attached.

[//]: # (- the operating system)

linux

[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

**Comment by misanthropos** [comment] 2018-09-12 05:09
I believe the problem is loyalty in Estoni - but is this intended? I mean the central SAM site is mine. Same for Alma and Cambria and Drassen is 100%. 
This might be related to being able to train militia in Estoni. That was not possible in vanilla i think.

**Comment by misanthropos** [comment] 2018-09-15 18:52
But Skyrider should never have been able to land there in the first place if its still occupied...

**Comment by JAsmine-ja2** [comment] 2019-01-26 18:03
You can fix the situation by fighting (and winning ;) a battle in Estoni. The shopper gets displayed in tactical view and works as intended.
[SaveGame01.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2799321/SaveGame01.zip)

**Comment by ja2-derek** [comment] 2020-07-10 15:36
I think I found some clues.

First of all, every sector is initialized as `fEnemyControlled = TRUE` when campaign starts:

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/f288e5da14768357a5fcf8e4b83ced1140919e33/src/game/Strategic/StrategicMap.cc#L2344-L2348

When a squad enters a it should set `fEnemyControlled` to false, if there are no enemies present.

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/99df5bc038547ddda3cb360a69c3cdcf29a947ed/src/game/Strategic/Strategic_Movement.cc#L1438-L1442

See the code above. If you never entered Estoni I6 on foot before, it will stay as `fEnemyControlled`. So I loaded the QuickSave, and ordered the squad to leave and a few minutes later re-enter I6, the issue is resolved. Fighting an enemy in sector is not necessary.

`is_heli_group` should only check for a flying heli group, not a landed heli group. Landed heli should be treated the same as a squad on foot.

**Comment by ja2-derek** [comment] 2020-07-10 15:59
I suspect it is this commmit - https://github.com/ja2-stracciatella/ja2-stracciatella/commit/f374ac72cc1c3b8aaf6a6a05d28418bff4552a18

The commit replaces `CheckForArrivalAtRefuelPoint` with `IsRefuelSiteInSector`, but `IsRefuelSiteInSector` does not consider if the refuel site is enabled (`fRefuelingSiteAvailable`)

**Closed** 2020-07-11 07:50 UTC
Labels: bug, major, non-vanilla
