### ISSUE TITLE
Crash on helicopter returning to airport when mercs present in sector.

### ISSUE THREAD

**Issue by LonCJ** [ja2-stracciatella/ja2-stracciatella#288] opened 2016-04-07 22:23 UTC
Master branch April 4th.  Game crashes when helicopter returns to Drassen airport and mercs are present in sector.  Error save and savegame in zip.  To replicate just have the helicopter leave and return with or without passengers.

[New Thread 0x7ffff2660700 (LWP 4389)]
[New Thread 0x7ffff1c4d700 (LWP 4391)]
ERROR: caught unhandled exception:
Failed to add node to world
Creating an emergency savegame succeeded (error.sav).
Please report this error with a description of the circumstances. Do not forget to attach the savegame.
[Thread 0x7ffff1c4d700 (LWP 4391) exited]
[Thread 0x7ffff7fd0780 (LWP 4385) exited]
[Inferior 1 (process 4385) exited with code 01]
(gdb) backtrace
No stack.

[helicopter_rtb_crash.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/209329/helicopter_rtb_crash.zip)

**Comment by derSteFfi** [comment] 2016-04-07 22:36
on first glance i guess a duplicate of #251

**Comment by LonCJ** [comment] 2016-04-08 15:23
And #158

**Closed** 2016-04-10 12:25 UTC
Labels: duplicate
