### ISSUE TITLE
Can't save games on Android since JA2S 0.19 20210920 build

### ISSUE THREAD

**Issue by Srandista** [ja2-stracciatella/ja2-stracciatella#1447] opened 2021-12-11 22:22 UTC
### What is wrong
Can't save games on Android since JA2S 0.19 20210920 build. If I use build 20210919, I can save game without issue, on build 20210920 I get an error message and game is not saved. I'm assuming, that breakage was introduced by PR #1401 

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.19 20210920 and up | JA2 1.06 EN  |    no    |    yes, on 0.19 20210919 and below     |

[//]: # Tried on 2 phones, Google Pixel 4a with Android 12 and Huawei P20 Pro with Android 10

**Comment by selaux** [comment] 2021-12-12 10:31
Thanks for the report. I can reproduce this as well. It seems it is caused by the game wanting to create a save game directory on save (which is already done on startup). The error message is:

```
2021-12-12 11:28:23.262 12421-12466/io.github.ja2stracciatella E/JA2: : Error saving game: FileMan::createDir('SavedGames-o-fortuna') failed: Fs_createDir "SavedGames-o-fortuna": Read-only file system (os error 30)
```
Those should probably be: `GCM->userPrivateFiles->createDir` calls.

**Comment by selaux** [comment] 2021-12-12 13:00
Should be closed in the next nightly release. Please reopen if it's still occuring.

**Closed** 2021-12-12 12:59 UTC

**Comment by Srandista** [comment] 2021-12-13 08:01
Thank you for the quick fix, just want to confirm, that nightly build indeed works!
