### ISSUE TITLE
Giving items to civilians in Drassen cause endless stopwatch

### ISSUE THREAD

**Issue by Podesta** [ja2-stracciatella/ja2-stracciatella#694] opened 2018-01-22 20:02 UTC
[//]: # (Thank you for taking the time to report an issue or propose an enhancement. Questions are also welcome.)
[//]: # (If you have more than one item to report, please open separate issues!)

[//]: # (This text will not be visible and you can freely delete it. Check the Preview tab for a cleaner look.)

### What is wrong
System is Xubuntu 16.04 LTS
When clearing Drassen (first mission) from soldiers, and after Deidranna cutscene, there was one kid that was begging for money. So I decided to give him some money. Doing so the little processing clock appeared and simply did not leave. I let the game run for over 30 min and nothing. I tested a bit more, and giving any item to any of the residents seem to cause the same behavior. I can not click anywhere, and the solution is to close and reload.

The only time I had attempted to give something to a civilian before was on the map before this one, on the factory. I attempted to give the factory manager a t-shirt and she said she would not accept gifts from me. So no bug on that case.

I can provide the savegame.

[//]: # (For bugs, please fill in this table [otherwise delete it]. The lines don't have to stay aligned.)

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  git 21/01/2018 | Steam JA2 Wildfire classic DLC |    probably    |    --     |

[//]: # (Please also include:)
[//]: # (- how to reproduce the bug and, if possible, a save game)
[//]: # (- the operating system)
[//]: # (- in case you know, for enhancements, if this feature was already added by some other source mod like 1.13)

[//]: # (When pasting backtraces or any other logs with hashed enumerations, please format it as a code block.)
[//]: # (You can do that by selecting it and clicking the "<>" icon or manually putting three backticks [```] at each end.)

EDIT: Just attempted importing the save on the steam version. Giving the cash to the same kid also made the game 'hang' indefinitely.

**Comment by Manuel-K** [comment] 2018-01-22 20:40
I'm not sure if that DLC contains modified data. 

Can you attach a txt file with the result of `find -type f -exec sha1sum '{}' \;`?

**Comment by Podesta** [comment] 2018-01-22 21:47
Do you need the whole thing or just the results from the steam folder and ja2stracciatella?

**Comment by Manuel-K** [comment] 2018-01-22 21:53
Only the results of the DLC folder, i.e. the folder that you selected in the launcher. Probably only the contents of the data folder that it should include, but the other stuff can't hurt.

**Comment by Manuel-K** [comment] 2018-01-22 21:57
The savegame could be useful as well. You have to zip or gzip it to attach it.

**Comment by Podesta** [comment] 2018-01-22 22:02
[trimmedja2log.txt](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1653726/trimmedja2log.txt)
[ja2log.txt](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1653727/ja2log.txt)

I made one with the whole ja2wildfire and one with only the data from the data from the dlc, especially since it is a wine version, so a ton of trash on the other file.

**Comment by Manuel-K** [comment] 2018-01-22 22:15
This is a cleaned up version of the checksum file:
[sha1sum.txt](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1653756/sha1sum.txt)


I'm removing your versions because they contain some private information.

**Comment by Manuel-K** [comment] 2018-01-22 22:22
Okay. There are many differences to my version. I've only got the GOG version.

**Comment by Podesta** [comment] 2018-01-22 22:30
If you import the save on the GOG version or stracciatella with GOG assets, does it not hang?

**Comment by Manuel-K** [comment] 2018-01-22 22:35
I'm too tired to do try that today.

**Comment by JAsmine-ja2** [comment] 2018-01-23 17:48
In vanilla JA2, it is not possible to give items to (nameless) civilians.
Can be tested in this savegame from Vanilla 1.12:
[SaveGame10.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1657022/SaveGame10.zip)
There is also a (named) NPC inside the building. Just teleport inside.

**Comment by Manuel-K** [comment] 2018-01-23 17:49
Got the same softlock on master with the GOG data. And with vanilla in wine as well.

**Comment by Manuel-K** [comment] 2018-01-23 17:52
@JAsmine-ja2 The same softlock is possible with your savegame as well.

It should not be possible to give an item to an unnamed civilian if it softlocks the game.

**Comment by chmallon** [comment] 2018-01-24 09:28
@Manuel-K: How do you give money to an unnamed civilian in vanilla?
I just see that you can throw the item.

**Comment by Manuel-K** [comment] 2018-01-24 09:45
Just like you can give it to named civilians. I don't know if it's possible in other versions, but you can do it in the GOG version.

**Comment by Podesta** [comment] 2018-01-24 10:02
With named civilians you can also use the talking menu, which is probably what he did. You can also use the right mouse click to cycle between throwing and, in this case, giving the item.

**Comment by JAsmine-ja2** [comment] 2018-01-24 15:09
@Podesta 
True, with RMB you can cycle between throw and give. Even in Vanilla JA2. This game never fails to surprise me with new things even after all these years :)
This is undocumented (at least in classic, non-GOG release) and probably not intended.
+1 to "It shouldn't be possible to give items to unnamed civilians."

**Comment by Manuel-K** [comment] 2018-01-29 17:36
The problem is caused because `HandleItemPointerClick()` is called while the global variable `gfItemPointerDifferentThanDefault` is `True`. This flips the value of `fGiveItem` to true (it was wrong because the target is not a named NPC. This path is also used to give items to other mercs. 

The obvious way to fix this is to only flip `fGiveItem` if the target is a merc.

**Comment by JAsmine-ja2** [comment] 2019-01-27 09:47
Shall we close this issue, since we have got #698 ?

**Closed** 2019-02-03 20:13 UTC
Labels: bug, minor, vanilla
