### ISSUE TITLE
Mac Sierra: Mouse pointer restricted when starting with -fullscreen

### ISSUE THREAD

**Issue by andreas12345** [ja2-stracciatella/ja2-stracciatella#459] opened 2016-12-14 11:04 UTC
I just built 409ae2a on Mac OS Sierra.

In windowed mode, or when switching to fullscreen mode after starting in windowed mode, everything seems to work fine.

When starting with "-fullscreen", the mouse pointer cannot access the lower and right ~20% of the screen, making the game unusable. This seems to be independent of resolution (happens in 640x480 as well as higher resolutions).

**Comment by lynxlynxlynx** [comment] 2016-12-14 12:19
Does the input box appear to be of fixed size or is it really bigger at higher resolutions as your 20% suggests?

**Comment by andreas12345** [comment] 2016-12-14 14:16
I have attached a few screenshots (created with Cmd+Shift+3) where I moved the mouse pointer to the rightmost corner. As you can see the limits depend on the resolution, but in a somewhat unpredictable way. The native screen resolution is 1680x1024. I did not scale the screenshots.

![640x480](https://cloud.githubusercontent.com/assets/3011215/21185211/07c80c00-c210-11e6-9a05-43889016dab7.png)
![800x600](https://cloud.githubusercontent.com/assets/3011215/21185212/07df316e-c210-11e6-8173-02a0d258a523.png)
![1024x768](https://cloud.githubusercontent.com/assets/3011215/21185213/07eba64c-c210-11e6-82ad-45d87d11151b.png)

**Comment by selaux** [comment] 2016-12-15 18:13
Can you try with the latest nightly from: http://builds-ja2.stefanlau.com/nightlies/? Maybe it is related to build on Sierra. I can't reproduce with latest nightly and El Capitan.

**Comment by monkeyphysics** [comment] 2017-01-23 19:43
I've had this issue on my retina MBP, which was related to dynamic graphics switching.
Try disabling this (System preferences > Energy Saver > top checkbox) and see if you still have the issue.

**Comment by selaux** [comment] 2017-10-29 12:31
Do we actually have anybody on macOS who can have a look at this?

**Comment by ja2-derek** [comment] 2020-04-07 10:24
I am not able to reproduce this with JA2:S 0.16.1, on MacOS Mojave. The mouse cursor works fine in with `-fullscreen`.

Automatic graphics switching is no longer an option in Energy Saver.

**Comment by lynxlynxlynx** [comment] 2020-04-07 21:04
Cool, closing then. Thanks.

**Closed by lynxlynxlynx** 2020-04-07 21:04 UTC
Labels: bug, macOS, non-vanilla, retest
