### ISSUE TITLE
CtD when travelling to I2

### ISSUE THREAD

**Issue by Tercus** [ja2-stracciatella/ja2-stracciatella#558] opened 2017-06-24 21:48 UTC
I2 is a sector south of Grumm, that is normally not accessible. You can travel to I3 and then walk in tactical view to the western edge of the map and manually travel to the sector. Once you arrive, the game crashes.

If memory serves me right, in vanilla, you'd arrive at an empty desert sector.

[QuickSave.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/1100021/QuickSave.zip)

**Comment by selaux** [comment] 2017-06-24 23:10
Duplicate of #492

**Closed by selaux** 2017-06-24 23:10 UTC
