### ISSUE TITLE
BUG: Android build( 0.17 or 0.18 pre-release) crash on Android 11 devices.

### ISSUE THREAD

**Issue by krukhlis** [ja2-stracciatella/ja2-stracciatella#1351] opened 2021-04-22 18:57 UTC
It's a bug with Android 11( maybe with all newer versions as well).
Android 0.17 and 0.18 pre-release builds crash on Android 11 when you attempt to pickup Data location folder.
At the same time both builds work like a charm on Android 9 devices.    

| JA2S version | Game version        | Vanilla bug? | Used to work? |
| ------------ | ------------------- | ------------ | ------------- |
|  0.18 pre-release or 0.17 release | eg. JA2 Gold English|    no    |    yes on Android 9|

1. Install it on Android 11 device. Even Andrpoid Studio Emulator with Android 11 target device will work to reproduce the bug.
2. Launch game
3. Click on "Choose" Data folder Location button.
4. Game immediately disappears( crashes).

No visual error pops-up.
I ran it under AS emulator and captured crash log( with some preceading info):

```
[0,46265728,com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity,userLeaving=false]
04-22 14:19:37.393   854   854 I wm_on_top_resumed_lost_called: [46265728,com.android.permissioncontroller.permission.ui.GrantPermissionsActivity,topStateChangedWhenResumed]
04-22 14:19:37.395   854   854 I wm_on_paused_called: [46265728,com.android.permissioncontroller.permission.ui.GrantPermissionsActivity,performPause]
04-22 14:19:37.399   564  1716 I wm_set_resumed_activity: [0,io.github.ja2stracciatella/.LauncherActivity,resumeTopActivityInnerLocked]
04-22 14:19:37.401   564  1716 I wm_resume_activity: [0,254543849,16,io.github.ja2stracciatella/.LauncherActivity]
04-22 14:19:37.401   564  1716 I wm_destroy_activity: [0,46265728,16,com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity,finish-imm:completePausedLocked]
04-22 14:19:37.407  6227  6227 I wm_on_activity_result_called: [254543849,io.github.ja2stracciatella.LauncherActivity,ACTIVITY_RESULT]
04-22 14:19:37.410   564   612 I ActivityManager: Killing 1766:com.android.providers.calendar/u0a68 (adj 975): empty #17
04-22 14:19:37.411   564   612 I am_kill : [0,1766,com.android.providers.calendar,975,empty #17]
04-22 14:19:37.411   564   612 I sysui_multi_action: [757,803,799,window_time_0,802,4]
04-22 14:19:37.417  6227  6227 D AndroidRuntime: Shutting down VM
04-22 14:19:37.419   854   854 I wm_on_stop_called: [46265728,com.android.permissioncontroller.permission.ui.GrantPermissionsActivity,LIFECYCLER_STOP_ACTIVITY]
04-22 14:19:37.419   854   854 I wm_on_destroy_called: [46265728,com.android.permissioncontroller.permission.ui.GrantPermissionsActivity,performDestroy]
--------- beginning of crash
04-22 14:19:37.420  6227  6227 E AndroidRuntime: FATAL EXCEPTION: main
04-22 14:19:37.420  6227  6227 E AndroidRuntime: Process: io.github.ja2stracciatella, PID: 6227
04-22 14:19:37.420  6227  6227 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {io.github.ja2stracciatella/io.github.ja2stracciatella.LauncherActivity}: java.lang.NullPointerException: Attempt to get length of null array
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4444)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.populateList(ChooserDialogFragment.java:262)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.initListView(ChooserDialogFragment.java:115)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.getLayout(ChooserDialogFragment.java:85)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.onCreateDialog(ChooserDialogFragment.java:300)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:417)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.Fragment.performGetLayoutInflater(Fragment.java:1322)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.FragmentController.execPendingActions(FragmentController.java:408)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:8119)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	... 11 more
04-22 14:19:37.421   854  6264 D OpenGLRenderer: endAllActiveAnimators on 0xe430b550 (RippleDrawable) with handle 0xb8e44eb0
04-22 14:19:37.424   564  1325 I am_crash: [6227,0,io.github.ja2stracciatella,954777158,java.lang.NullPointerException,Attempt to get length of null array,ChooserDialogFragment.java,262]
04-22 14:19:37.448   564  6269 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
04-22 14:19:37.452   321   321 I Zygote  : Process 1766 exited due to signal 9 (Killed)
04-22 14:19:37.453   564  1325 W ActivityTaskManager:   Force finishing activity io.github.ja2stracciatella/.LauncherActivity
04-22 14:19:37.453   564  1325 I wm_finish_activity: [0,254543849,16,io.github.ja2stracciatella/.LauncherActivity,force-crash]
04-22 14:19:37.453   564  1325 I wm_focused_stack: [0,0,15,16,finish-top adjustFocusToNextFocusableStack]
04-22 14:19:37.484   564  1325 I wm_pause_activity: [0,254543849,io.github.ja2stracciatella/.LauncherActivity,userLeaving=false]
04-22 14:19:37.489   564  1716 I am_proc_died: [0,1766,com.android.providers.calendar,975,19]
04-22 14:19:37.489   564  1325 I sysui_multi_action: [757,316,758,4,759,-1]

```

It looks like it's NPE that happens when you guys construct "Choose Folder dialog":

```
04-22 14:19:37.420  6227  6227 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.populateList(ChooserDialogFragment.java:262)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.initListView(ChooserDialogFragment.java:115)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.getLayout(ChooserDialogFragment.java:85)
04-22 14:19:37.420  6227  6227 E AndroidRuntime: 	at com.codekidlabs.storagechooser.fragments.ChooserDialogFragment.onCreateDialog(ChooserDialogFragment.java:300)

```

**Comment by lynxlynxlynx** [comment] 2021-04-22 19:05
Hi, this is a duplicate of just closed #1348. 

How did you find out about the young port, that we get two similar reports in such a short succession?

**Closed by lynxlynxlynx** 2021-04-22 19:05 UTC

**Comment by selaux** [comment] 2021-04-22 21:04
Can you retest with this build: https://storage.googleapis.com/ja2-builds/releases/v0.18.0/ja2-stracciatella_0.18.0-+256e4d2_android.apk? It should be fixed there.

**Comment by Srandista** [comment] 2021-04-22 21:12
I can confirm, that this new build works as expected. Thank you for super quick fix!

**Comment by krukhlis** [comment] 2021-04-22 22:51
I can also confirm. It works in Android Studio Emulator with Android11 device emulation like a charm. Thank you. Will share the link with forum community that reported this issue to me based on their A11 devices experience.
