### ISSUE TITLE
Runtime error in sector I2

### ISSUE THREAD

**Issue by kavol** [ja2-stracciatella/ja2-stracciatella#492] opened 2017-02-07 19:28 UTC
I'm getting "runtime error" ... load the save, go to map, choose sector I2 and compress the time to reproduce it.
[QSI2.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/758764/QSI2.zip)

**Comment by momoko-h** [comment] 2017-02-08 11:33
The problem is that there is a squad moving to sector I2, which is impassable. The runtime error occurs when the game tries to load the radar map for that sector. Since you're not supposed to be able to enter it, the file radarmaps/I2.SLI simply does not exist. 

Do you remember how you managed to send your squad to I2? Btw, you can continue that game by setting a new destination for squad 6.

**Comment by kavol** [comment] 2017-02-08 13:13
I've just moved the squad to southwest corner of I3 and sent them west (and yes, I was able to continue the game by rerouting them)

**Comment by JAsmine-ja2** [comment] 2017-06-07 19:23
Moving into sector L2 from the east is possible even in Vanilla JA2, while it should not be!

ja2-stracciatella/src/game/Strategic/Strategic_Movement_Costs.cc 

Is the place, where this could be changed.

**Comment by chmallon** [comment] 2017-06-13 11:16
There are two pairs of sectors, where traversal is allowed, but one sector does not exist.
Also there is one pair of sectors for which traversal is not allowed but both sectors exist and there is no apparent reason on the maps, why traversal should be forbidden.
(There are 3 more pairs for which traversal is forbidden but these look fine, i.e. there is a cliff or water.)

**Closed** 2020-07-11 07:47 UTC
Labels: bug, major, vanilla
