### ISSUE TITLE
Launcher - ideas & minor enhancements

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#638] opened 2017-12-16 15:17 UTC
Testing the win 64 release of 0.16.0

1) The user is able to edit the predefined resolutions. This shouldn't be possible.

1a) The user is also able to edit the language selection field. Shouldn't be possible, too.

2) The warning box when using an invalid custom resolution has no "heading" (text in the upper frame). It could have a heading like "Warning".

3) After the warning for invalid resolution pops up, the launcher could reset the custom resolution to 640x480 for added convenience. Right now, this has to be done manually.

4) When selecting an invalid data directory, the launcher shows a warning when launching the game. However, the warning is very unclear:
![launcher](https://user-images.githubusercontent.com/17213795/34071783-508c2ec0-e27c-11e7-89d9-fb2eaf133751.jpg)

4a) We also need an appropriate warning for wrong language selected. ATM, it is the same warning as 4)

5) Maybe, the launcher could already check for correct data files when selecting the data directory (and not wait until you try to launch the game).

5.1) The same is true for the editor, which needs specific files (editor.slf)

~~6) The launcher executable itself could maybe use the logo.~~ (duplicate of #607)

![logo](https://user-images.githubusercontent.com/17213795/34072393-f13d34c2-e286-11e7-8540-847ab6aca883.jpg)

7) Should the launcher be renamed to

"stracciatella launcher" ? Beacuse that is, what it does. It can't launch regular JA2.

**Comment by JAsmine-ja2** [comment] 2017-12-16 16:31
The launcher executable itself could maybe use the logo.

![logo](https://user-images.githubusercontent.com/17213795/34072393-f13d34c2-e286-11e7-8540-847ab6aca883.jpg)

**Comment by JAsmine-ja2** [comment] 2017-12-16 16:32
7) Should the launcher be renamed to

"stracciatella launcher" ?

**Comment by Manuel-K** [comment] 2017-12-16 20:47
Some of those things are duplicates of #607.

1. True, but I don't know if it is possible to prevent that.
2. I know, but I don't think FLTK supports changing the title of predefined warning boxes. If we want to create a custom form, we could choose the title.
3. IMO a bad idea. I hate it when programs do that. Imagine a small typo that you do not notice, the warning pops up and you have to start again because everything you've entered is gone.
4. Yes, the  error message is horrible and not useful for the end user, but this is not a part of the launcher. The error message is caused by ja2.exe dying – we should definitely change that.
5. It seems to be a good idea to add some kind of validation to the launcher as well. If `editor.slf` isn't found, the edit button could be greyed out or (preferably) a warning box could be displayed.
6. Already in #607 as Use logo as exe icon (Windows)/Use logo as App Bundle icon (macOS)
7. Not possible at the moment. The launcher finds `ja2.exe` (on Windows) or the corresponding binary for the other operation systems by using it's own path minus the `-launcher` part.

**Comment by JAsmine-ja2** [comment] 2017-12-16 21:43
Thinking about it, you're probably right about 3)

**Comment by JAsmine-ja2** [comment] 2017-12-16 22:25
8) When a game is running, trying to close the launcher results in the launcher crashing.

**Comment by lynxlynxlynx** [comment] 2019-07-08 18:03
@JAsmine-ja2 you'll be happy to know the launcher has been slightly reworked, also addressing some of the points mentioned here. Once the build is up, please go through the suggestions here and cross out anything that's not relevant any more. Ideally all the actual work to be done should be collated in the first post.

**Comment by selaux** [comment] 2022-03-06 10:15
I think all of the relevant suggestions have already been applied. Closing.

**Closed by selaux** 2022-03-06 10:15 UTC
Labels: launcher
